### ISSUE TITLE
[Request] Option for those who disable autoplaying of videos

### ISSUE THREAD

**Issue by vzjrz** [DanielKamkha/PlayPause#12]
I use a userscript/addon (https://github.com/ParticleCore/Particle) to disable the autoplaying of all youtube videos. The way I usually use youtube is by opening several youtube tabs at the same time and playing only one while leaving the rest in the background with the player not loaded/playing. Using your addon (an amazingly useful addon!) unfortunately clouds my tabs with a multitude of pause-icons making it very hard to keep track of which tab I'm currently watching/listening to when pausing. Could you please add an option to not automatically add the pause-icon to tabs and only add the pause-icon when the user manually clicks the play-icon to pause the video. So basically if the video is in a paused state without having been paused through your addon's icons the tab should not have any pause/play icons.

*Edit: This would also 'fix' the icon showing up in youtube search pages and user/videos pages.

**Comment by DanielKamkha** [comment]
That's an interesting idea for an enhancement. I could add this in some future release, when I have time.

**Comment by DanielKamkha** [comment]
Play/Pause v2.0 (in repo, not published on AMO yet) uses WebExtensions API, which is incapable of responding to "click on tab title" event. Main functionality will thus be changed to respond to the "mute" button instead.
