### ISSUE TITLE
Pause symbol shows up on YouTube front page

### ISSUE THREAD

**Issue by DanielKamkha** [DanielKamkha/PlayPause#22]
Pause symbol shows up on YouTube front page. Also shows up (erroneously) at youtube.com/user/\* and youtube.com/channel/*

**Comment by R0maric** [comment]
I found a possibility, [pageshow](https://developer.mozilla.org/en-US/docs/Web/Events/pageshow) or DOMContentLoaded
`const win = require('sdk/window/utils').getMostRecentBrowserWindow();`
`function urlChange(e) {`
`     if (e.target.URL.startsWith('https://www.youtube.com/')) console.error(e.target.URL);`
`}`
`win.addEventListener("pageshow", urlChange, false);`

**Comment by DanielKamkha** [comment]
Play/Pause v2.0 (in repo, not published on AMO yet) uses WebExtensions API, which is incapable of responding to "click on tab title" event. Main functionality will thus be changed to respond to the "mute" button instead.
