### ISSUE TITLE
Mozilla store

### ISSUE THREAD

**Issue by ZatsuneNoMokou** [DanielKamkha/PlayPause#42]
Could you send the Web Extension version on the Mozilla store as beta to let people access if they want to, before Firefox 57?

**Comment by DanielKamkha** [comment]
Done. https://addons.mozilla.org/firefox/downloads/latest-beta/play-pause/addon-625966-latest.xpi?src=dp-btn-devchannel

**Comment by mickael49300fr** [comment]
thank you
