### ISSUE TITLE
Web Extension Troubles

### ISSUE THREAD

**Issue by ZatsuneNoMokou** [DanielKamkha/PlayPause#43]
![screenshot at 21h41m52s](https://user-images.githubusercontent.com/7016954/29430636-69a520d8-8395-11e7-99bb-99bdc17cc4ea.png)

The addon button have the default icon, and there wasn't supposed to have a context menu on tabs?

I know you wasn't planning to publish it now, so I leave it here, but I know (having an addon myself) that Firefox still have annoying bugS with Web Extensions.

**Comment by DanielKamkha** [comment]
Button icon is simply not there yet. Also, there is no additional context menu item, "Mute tab" should do the trick.
