### ISSUE TITLE
Not showing up as web extension

### ISSUE THREAD

**Issue by MFeldpausch** [DanielKamkha/PlayPause#46]
First of all, this addon is great.  I was really disappointed that it would not work when legacy extensions died.  However, it shows here (https://github.com/DanielKamkha/PlayPause/commit/0f1342626b00ec7a22d4ba8cc4530048b31e9f96) that it was converted to a web extension.  However, Firefox does not think that it is:
![pplegacy](https://user-images.githubusercontent.com/32279084/30829832-f47ef2a4-a20f-11e7-8e91-bee5706e5a20.JPG)
And on the site:
![pplegacysite](https://user-images.githubusercontent.com/32279084/30829852-094798c6-a210-11e7-9ed3-26c4ccecb140.JPG)
It should be:
![pplegacysite2](https://user-images.githubusercontent.com/32279084/30829863-13c56e0e-a210-11e7-8d1c-6a13079f6af3.JPG)
Thanks for looking into it.

**Comment by DanielKamkha** [comment]
Explanation: https://github.com/DanielKamkha/PlayPause/issues/40

Beta link: https://addons.mozilla.org/firefox/downloads/latest-beta/play-pause/addon-625966-latest.xpi?src=dp-btn-devchannel
