### ISSUE TITLE
Play/Pause doesn't work in Firefox 57

### ISSUE THREAD

**Issue by adrian3d** [DanielKamkha/PlayPause#47]
Hey ! Great extension but finally doesn't work with Firefox new extension API.

Can you fix it, please ?

**Comment by DanielKamkha** [comment]
Explanation: https://github.com/DanielKamkha/PlayPause/issues/40

Beta link: https://addons.mozilla.org/firefox/downloads/latest-beta/play-pause/addon-625966-latest.xpi?src=dp-btn-devchannel

**Comment by adrian3d** [comment]
Great ! Thank you !
