### ISSUE TITLE
Stopped working on Spotify?

### ISSUE THREAD

**Issue by HarveyWilliams** [DanielKamkha/PlayPause#51]
I'm pretty sure this extension was working with Spotify (https://open.spotify.com), but when testing today, it doesn't seem to be any more.

It does still work on YouTube.

Tested on Firefox 57.0.1 (64-bit).

Can anyone else confirm?

**Comment by DanielKamkha** [comment]
Fixed in https://github.com/DanielKamkha/PlayPause/commit/b8f4ed7169968575a9c7b9e7ac750b3aea189100. Uploaded to AMO as v2.0.3.

**Comment by HarveyWilliams** [comment]
Nice. Such a simple fix too. Thanks for the speed!
